#!/bin/sh

# Colored manpages
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export EDITOR="vim"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse"

# Test if current environnement is wsl2
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    export DISPLAY=$(ip route list default | awk '{print $3}'):0
    export LIBGL_ALWAYS_INDIRECT=1
    alias i3='sudo mount --bind /mnt/c/Users/clego/OneDrive\ -\ ESEO/Cours/I3 ~/I3/'
    alias i2='sudo mount --bind /mnt/c/Users/clego/OneDrive\ -\ ESEO/Cours/I2 ~/I2/'
    alias i='i2 && i3'
fi

#My aliases
alias ll='exa -laF --group-directories-first --header --long'
alias la='exa -a --group-directories-first'
alias l='exa -lF --group-directories-first --header --long'

alias up='sudo apt-get update -y && sudo apt-get upgrade -y'
alias reload='echo "Sourcing environnement"; source ~/.zshrc'

alias k='ps -ef | fzf | awk '{print $2}' | xargs kill -9'
alias findall='find * | fzf --prompt 'All> ' \
             --header 'CTRL-D: Directories / CTRL-F: Files' \
             --bind 'ctrl-d:change-prompt(Directories> )+reload(find * -type d)' \
             --bind 'ctrl-f:change-prompt(Files> )+reload(find * -type f)''

gdiff() {
  preview="git diff $@ --color=always -- {-1}"
  git diff $@ --name-only | fzf -m --ansi --preview $preview
}

